name: 'Github Actions Notifier - Slack'
description: 'This action will send a notification to Slack'
author: 'codigube'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'bell'
  color: 'orange'
